name: Pull Request Build

on:
  workflow_call:
    inputs:
      builder:
        required: false
        type: string
        default: 'maven'

env:
  CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
  CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
          java-package: jdk
          architecture: x64
      - name: Run build
        run: |
          if [[ “${{ inputs.builder }}” == *“maven”* ]]; then
            ./mvnw clean verify
          else
            ./gradlew test
          fi
