name: On-Tag Release Stage Workflow

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string


env:
  CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
  CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  GH_TOKEN: ${{ secrets.GH_GRUNTY_OAUTH_TOKEN }}
  
jobs:

  build_deploy_stage:
    uses: tagsource/ci-tagsource/.github/workflows/build-deploy-workflow.yml@main
    secrets: inherit
    with:
      env: stage
      tag: ${{  github.ref_name }}
      action: Deploy

  create_release:
    needs: build_deploy_stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch git tags
        id: git-fetch
        run: |
          git fetch -a
          echo ::set-output name=previous_tag::$(git tag --sort version:refname | tail -2 | head -1)
          git tag --sort "-committerdate" 

      - name: Build Release notes
        id: changes
        run: |
          #git log --no-merges --pretty=format:"%s - author: %cn" '${{ steps.git-fetch.outputs.previous_tag }}^'..${{ github.ref }} 
          # export DIFF=$(git log --no-merges --pretty=format:"%s - author: %cn" '${{ steps.git-fetch.outputs.previous_tag }}^'..${{ github.ref }} )
          echo ::set-output name=diff::$(git log --no-merges --pretty=format:"%s - author: %cn" '${{ steps.git-fetch.outputs.previous_tag }}^'..${{ github.ref }} | sed ':a;N;$!ba;s/\n/%0A/g' )

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.changes.outputs.diff }}
          draft: true
          prerelease: true
          
      - name: Label PR in release
        id: pr_history_label
        run: |
          pr_list=$(git log --merges --grep 'Merge pull request' --pretty=format:%s '${{ steps.git-fetch.outputs.previous_tag }}^'..${{ github.ref }} )
          echo $pr_list
          #echo ::set-output name=diff::$(git log --merges --grep 'Merge pull request' --pretty=format:%s '${{ steps.git-fetch.outputs.previous_tag }}^'..${{ github.ref }} )
          while read pr; do
            pr_id=$(echo $pr | awk '{print $4}' | sed 's/#//')
            echo $pr_id
            gh pr edit $pr_id --add-label "released_stage,${{ github.ref }}"
          done <<< "$pr_list"

